-- Criar banco de dados
CREATE DATABASE Desafio_prod;

-- Usar o banco de dados
USE Desafio_prod;

-- Criar tabela
CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY,
	NOME VARCHAR(300),
	CPF VARCHAR(11),
    LOGIN VARCHAR(100),
    SENHA VARCHAR(100),
    DATACADASTRO DATE
);

-- Criar tabela
CREATE TABLE PRODUTOS (
    ID INT PRIMARY KEY,
    NOME VARCHAR(500),
    FORNECEDOR VARCHAR(500),
	QUANTIDADE INT,
    DATACADASTRO DATE
);

-- Criar uma tabela
CREATE TABLE FORNECEDORES (
    ID INT PRIMARY KEY,
    NOME VARCHAR(500),
    CNPJ VARCHAR(13),
	ENDERECO VARCHAR(500),
	ATIVO VARCHAR(1),
    DATACADASTRO DATE
);